### ISSUE TITLE
Help button goes to wrong page

### ISSUE THREAD

**Issue by henspace** [henspace/text2lesson#24]
The help button goes to the about page in the text2lesson docs. It should go to a dedicated help page.

**Comment by burhanharoon** [comment]
Hi @henspace, can you assign this to me, I'll fix it and then create a PR. Sounds good?

**Comment by henspace** [comment]
Hi [burhanharoon](https://github.com/burhanharoon),
Thanks for the offer. I've literal just sorted this in a different branch.
I didn't realise anyone would have noticed this project yet as it's very early days :)
